# $HOME/.config/alacritty/alacritty.toml

[general]
live_config_reload = true
# import = ["themes/vague.toml"]

[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font Propo"
style = "Regular"

[window]
opacity = 0.8
blur = true
dynamic_padding = true

[window.padding]
x = 8
y = 8

[selection]
save_to_clipboard = true

[colors.primary]
background = "#222222"
foreground = "#d3c6aa"

[colors.normal]
black   = "#4b565c"
red     = "#e67e80"
green   = "#a7c080"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#d3c6aa"

[colors.bright]
black   = "#4b565c"
red     = "#e67e80"
green   = "#a7c080"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#d3c6aa"
