# $HOME/.config/alacritty/alacritty.toml

[general]
live_config_reload = true
import = ["themes/everforest.toml"]
# import = ["themes/vague.toml"]

[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font Propo"
style = "Regular"

[window]
opacity = 0.8
blur = true
dynamic_padding = true

[window.padding]
x = 8
y = 8

[selection]
save_to_clipboard = true
